<?php

namespace Framing33\AlpabCitoyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantAlphabetisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantAlphabetisationRepository extends EntityRepository
{
}
